# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_name = "Docker Master"
vm_root = "/var/www"
vm_ip = "192.168.33.211"

Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64" # TODO: replace with own box
  config.vm.hostname = "docktor-master"
  config.vm.boot_timeout = 720

  config.vm.network "private_network", ip: vm_ip

  # VMWare-specific settings
  config.vm.provider "vmware_fusion" do |v, override|
    #v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["displayname"] = vm_name

    # No need for NFS for VMWARE
    override.vm.synced_folder "../data/www", vm_root
  end

  # init docker and setup environment
  config.vm.provision "shell", path: "../bin/init_docker_master.sh"

end
