# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_name = "Docktor Application Server"
vm_root_dir = "/var/www"
vm_ip = "192.168.35.122"
vm_hostname = "docktor-master"
vm_modulepath = "/etc/puppet/modules"
vm_hieradata_dir = "/etc/puppet/hieradata"
vm_bin = "/usr/local/bin"
vm_user = "vagrant"
vm_group = "docker"

Vagrant.configure(2) do |config|
  config.vm.box_url = "https://atlas.hashicorp.com/zig-zag/docktor-master-test"
  config.vm.box = "zig-zag/docktor-master-test"
  config.vm.box_check_update = true

  config.vm.hostname = vm_hostname
  config.vm.boot_timeout = 720
  config.vm.post_up_message = "Add to /etc/hosts line: #{vm_ip} #{vm_hostname}"

  config.vm.network "private_network", ip: vm_ip

  # VMWare-specific settings
  config.vm.provider "vmware_fusion" do |v, override|
    #v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["displayname"] = vm_name

    # No need for NFS for VMWARE
    override.vm.synced_folder "../data", vm_root_dir, owner: vm_user, group: vm_group
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true # disable syn to "/vagrant" folder
  config.vm.synced_folder "./docker", "/data/docker", type: "rsync"
  config.vm.synced_folder "puppet/modules", vm_modulepath
  config.vm.synced_folder "puppet", "/etc/puppet", type: "rsync", rsync__exclude: ["modules/"]
  config.vm.synced_folder "~/.ssh", "/home/vagrant/.ssh_host", type: "rsync", rsync__exclude: ["authorized_keys"]

  # copy binaries
  config.vm.synced_folder "../bin", vm_bin, type: "rsync"

  # copy files from host to guest
  config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
  config.vm.provision "file", source: "~/.gitignore_global", destination: "~/.gitignore_global"

  # init docker and setup environment
  config.vm.provision "shell", name: "Setup server configuration", path: "../bin/provision.sh"

  config.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = "rsync"
      puppet.manifests_path = "puppet"
      puppet.manifest_file = "site.pp"
      puppet.options = "--yamldir #{vm_hieradata_dir}"
      puppet.hiera_config_path = "puppet/hiera.yaml"
      puppet.module_path = "puppet/modules"
    end
end
