# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_name = "Docker Master"
vm_root = "/var/www"
vm_ip = "192.168.33.211"
vm_host = "docktor-master"

Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64" # TODO: replace with own box
  config.vm.hostname = vm_host
  config.vm.boot_timeout = 720
  config.vm.post_up_message = "Add to /etc/hosts line: #{vm_ip} #{vm_host}"

  config.vm.network "private_network", ip: vm_ip

  # VMWare-specific settings
  config.vm.provider "vmware_fusion" do |v, override|
    #v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["displayname"] = vm_name

    # No need for NFS for VMWARE
    override.vm.synced_folder "../data/www", vm_root
  end

  # copy files from host to guest
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/host_id_rsa.pub"

  # init docker and setup environment
  config.vm.provision "shell", path: "../bin/init_docker_master.sh"

  # puppet install
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file = "docker_master.pp"
    puppet.hiera_config_path = "puppet/hiera.yaml"
    #puppet.working_directory = "/tmp/vagrant-puppet"
  end

  config.push.define "atlas" do |push|
    push.app = "zig-zag/docktor-master-test"
    push.vcs = false # set to true later
    push.token = "pNnk770yzhGVqA.atlasv1.4eXCQMszLw0mnerxhdilC5vgdS9dptgkQefiVVji1rVk7GgHBjSm2u6nXpYXVcHW8Ls"
    push.dir = "atlas-packer-vagrant"
  end
end
