FROM richarvey/nginx-php-fpm:stable

LABEL Description="Contains basic setup for NGINX-PHP-FPM setup" Vendor="Exclusive Home Production" Version="1.0"

COPY ./default.dev.vhost.conf /etc/nginx/sites-available/default.conf